version: 2

defaults: &defaults
  working_directory: ~/flask-arrested
  docker:
    - image: python:3

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 setup.py develop
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . ~/flask-arrested/venv/bin/activate
            python3 setup.py develop
            py.test -s --cov=arrested --cov-report=term-missing --tb=short tests/
      - run:
          command: |
            . ~/flask-arrested/venv/bin/activate
            python setup.py develop
            py.test -s --cov=arrested --cov-report=term-missing --tb=short tests/

  release:
    <<: *defaults
    steps:
      - checkout
      - deploy:
          command: |
            pip install twine
            python setup.py sdist
            python setup.py bdist_wheel --universal
            twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
            curl -X POST http://readthedocs.org/build/arrested
  docs:
    <<: *defaults
    steps:
      - checkout
      - deploy:
          command: |
            curl -X POST http://readthedocs.org/build/arrested

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          filters:
            branches:
              only:
                - master
                - wip/version-0.1.0
          requires:
            - test
      - docs:
          requires:
            - test
