version: 2

defaults: &defaults
  working_directory: ~/flask-arrested

notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/4f299d4d1b02cb3a60b9

jobs:
  build-python3:
    <<: *defaults
    docker:
      - image: python:3
    steps:
      - checkout
      - restore_cache:
          key: py3deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv py3venv
            . py3venv/bin/activate
            pip install -r requirements.txt
            python3 setup.py develop
      - save_cache:
          key: py3deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "py3venv"
  build-python2:
    <<: *defaults
    docker:
      - image: python:2
    steps:
      - checkout
      - restore_cache:
          key: py2deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            [ -d py2venv ] && echo 'exists' || virtualenv py2venv
            . py2venv/bin/activate
            pip install -r requirements.txt
            python setup.py develop
      - save_cache:
          key: py2deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "py2venv"

  test-python3:
    <<: *defaults
    docker:
      - image: python:3
    steps:
      - checkout
      - restore_cache:
          key: py3deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . ~/flask-arrested/py3venv/bin/activate
            python3 setup.py develop
            py.test -s --cov=arrested --cov-report=term-missing --tb=short tests/
      - save_cache:
          key: py3testreport-{{ .Branch }}-{{ .Revision }}
          paths:
            - "py3venv"
            - ".coverage"

  test-python2:
    <<: *defaults
    docker:
      - image: python:2
    steps:
      - checkout
      - restore_cache:
          key: py2deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            . ~/flask-arrested/py2venv/bin/activate
            python setup.py develop
            py.test -s --cov=arrested --cov-report=term-missing --tb=short tests/
      - save_cache:
          key: py2testreport-{{ .Branch }}-{{ .Revision }}
          paths:
            - "py2venv"
            - ".coverage"

  release:
    <<: *defaults
    docker:
      - image: python:3
    steps:
      - checkout
      - deploy:
          command: |
            pip install twine
            python setup.py sdist
            python setup.py bdist_wheel --universal
            twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
            curl -X POST http://readthedocs.org/build/arrested

  coverage:
    <<: *defaults
    docker:
      - image: python:3
    steps:
      - checkout
      - restore_cache:
          key: py3testreport-{{ .Branch }}-{{ .Revision }}
      - run:
          command: |
            . ~/flask-arrested/py3venv/bin/activate
            coveralls
  docs:
    <<: *defaults
    docker:
      - image: python:3
    steps:
      - checkout
      - deploy:
          command: |
            curl -X POST http://readthedocs.org/build/arrested

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build-python2
      - build-python3
      - test-python2:
          requires:
            - build-python2
      - test-python3:
          requires:
            - build-python3
      - release:
          filters:
            branches:
              only:
                - master
                - wip/version-0.1.0
          requires:
            - test-python2
            - test-python3
      - docs:
          requires:
            - test-python2
            - test-python3
      - coverage:
          requires:
            - test-python2
            - test-python3
